# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - nightly
  - 0.7
notifications:
  email: false
#script:
  #- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  #- julia --color=yes -e "VERSION >= v\"0.7.0-DEV.5183\" && using Pkg; Pkg.clone(pwd()); Pkg.build(\"${JL_PKG}\"); Pkg.test(\"QuantumBayesian\", coverage=true)"
after_success:
  # push coverage results to Coveralls
  #- julia -e 'cd(Pkg.dir("QuantumBayesian")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia --color=yes -e 'VERSION >= v\"0.7.0-DEV.5183\" && using Pkg; cd(Pkg.dir("QuantumBayesian")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
